CREATE TABLE beneficiaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    beneficiary_account_number VARCHAR(32) NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    beneficiary_name VARCHAR(255),
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_beneficiaries_owner_account UNIQUE (owner_user_id, beneficiary_account_number),
    CONSTRAINT beneficiaries_status_check CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE INDEX idx_beneficiaries_owner_user_id ON beneficiaries (owner_user_id);
