CREATE TABLE transactions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	event_id VARCHAR(64) NOT NULL,
	transaction_reference VARCHAR(64) NOT NULL,
	sender_user_id BIGINT NOT NULL,
	receiver_user_id BIGINT NOT NULL,
	sender_account_number VARCHAR(32) NOT NULL,
	receiver_account_number VARCHAR(32) NOT NULL,
	amount NUMERIC(19, 2) NOT NULL,
	currency VARCHAR(3) NOT NULL,
	description VARCHAR(240),
	status VARCHAR(32) NOT NULL,
	completed_at TIMESTAMP NOT NULL,
	created_at TIMESTAMP NOT NULL,
	CONSTRAINT uk_transactions_event_id UNIQUE (event_id),
	CONSTRAINT uk_transactions_reference UNIQUE (transaction_reference)
);

CREATE INDEX idx_transactions_sender_user_created_at
	ON transactions (sender_user_id, created_at DESC);

CREATE INDEX idx_transactions_receiver_user_created_at
	ON transactions (receiver_user_id, created_at DESC);
