spring.application.name=beneficiaryservice
server.port=8084

spring.datasource.url=jdbc:postgresql://localhost:5547/beneficiarydb
spring.datasource.username=payflux
spring.datasource.password=beneficiaryAdmin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

app.jwt.secret=there-is-a-secret-key-for-jwt-token-generation-in-authservice
app.kafka.topics.beneficiary-added=beneficiary-added
app.services.account-service.base-url=http://localhost:8081
