spring.application.name=gatewayservice
server.port=${GATEWAYSERVICE_PORT:8088}

payflux.services.auth=${AUTHSERVICE_BASE_URL:http://localhost:8080}
payflux.services.account=${ACCOUNTSERVICE_BASE_URL:http://localhost:8081}
payflux.services.notification=${NOTIFICATIONSERVICE_BASE_URL:http://localhost:8082}
payflux.services.wallet=${WALLETSERVICE_BASE_URL:http://localhost:8083}
payflux.services.beneficiary=${BENEFICIARYSERVICE_BASE_URL:http://localhost:8084}
payflux.services.transaction=${TRANSACTIONSERVICE_BASE_URL:http://localhost:8086}
payflux.services.audit=${AUDITSERVICE_BASE_URL:http://localhost:8087}

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://127.0.0.1:5173}
app.jwt.secret=${JWT_SECRET}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true
info.app.name=${spring.application.name}
logging.pattern.level=%5p [${spring.application.name:unknown},%X{correlationId:-}]
