CREATE TABLE wallets (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	owner_user_id BIGINT NOT NULL,
	account_id BIGINT NOT NULL,
	account_number VARCHAR(32) NOT NULL,
	full_name VARCHAR(160) NOT NULL,
	email VARCHAR(190) NOT NULL,
	currency VARCHAR(3) NOT NULL,
	available_balance NUMERIC(19, 2) NOT NULL DEFAULT 0,
	status VARCHAR(32) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	version BIGINT NOT NULL DEFAULT 0,
	CONSTRAINT uk_wallets_owner_user_id UNIQUE (owner_user_id),
	CONSTRAINT uk_wallets_account_id UNIQUE (account_id),
	CONSTRAINT uk_wallets_account_number UNIQUE (account_number)
);

CREATE TABLE wallet_transactions (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	wallet_id BIGINT NOT NULL,
	counterparty_wallet_id BIGINT,
	transaction_reference VARCHAR(64) NOT NULL,
	type VARCHAR(32) NOT NULL,
	status VARCHAR(32) NOT NULL,
	amount NUMERIC(19, 2) NOT NULL,
	currency VARCHAR(3) NOT NULL,
	description VARCHAR(240),
	counterparty_account_number VARCHAR(32),
	created_at TIMESTAMP NOT NULL,
	CONSTRAINT fk_wallet_transactions_wallet
		FOREIGN KEY (wallet_id) REFERENCES wallets (id),
	CONSTRAINT fk_wallet_transactions_counterparty_wallet
		FOREIGN KEY (counterparty_wallet_id) REFERENCES wallets (id),
	CONSTRAINT uk_wallet_transactions_reference UNIQUE (transaction_reference)
);

CREATE INDEX idx_wallet_transactions_wallet_created_at
	ON wallet_transactions (wallet_id, created_at DESC);
