CREATE TABLE outbox_events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	event_id VARCHAR(64) NOT NULL,
	topic VARCHAR(120) NOT NULL,
	event_type VARCHAR(160) NOT NULL,
	aggregate_type VARCHAR(80) NOT NULL,
	aggregate_id VARCHAR(80) NOT NULL,
	payload TEXT NOT NULL,
	status VARCHAR(32) NOT NULL,
	attempts INTEGER NOT NULL DEFAULT 0,
	last_error VARCHAR(500),
	created_at TIMESTAMP NOT NULL,
	published_at TIMESTAMP,
	CONSTRAINT uk_outbox_events_event_id UNIQUE (event_id)
);

CREATE INDEX idx_outbox_events_status_created_at
	ON outbox_events (status, created_at);
