CREATE TABLE wallet_ledger_entries (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	wallet_id BIGINT NOT NULL,
	transaction_reference VARCHAR(80) NOT NULL,
	entry_type VARCHAR(16) NOT NULL,
	amount NUMERIC(19, 2) NOT NULL,
	balance_after NUMERIC(19, 2) NOT NULL,
	currency VARCHAR(3) NOT NULL,
	description VARCHAR(240),
	created_at TIMESTAMP NOT NULL,
	CONSTRAINT fk_wallet_ledger_entries_wallet
		FOREIGN KEY (wallet_id) REFERENCES wallets (id),
	CONSTRAINT uk_wallet_ledger_entries_wallet_reference UNIQUE (wallet_id, transaction_reference)
);

CREATE INDEX idx_wallet_ledger_entries_wallet_created_at
	ON wallet_ledger_entries (wallet_id, created_at DESC);

INSERT INTO wallet_ledger_entries (
	wallet_id,
	transaction_reference,
	entry_type,
	amount,
	balance_after,
	currency,
	description,
	created_at
)
SELECT
	id,
	'MIGRATION-OPENING-' || id,
	'CREDIT',
	available_balance,
	available_balance,
	currency,
	'Opening balance migrated from wallet projection',
	CURRENT_TIMESTAMP
FROM wallets
WHERE available_balance > 0;
