CREATE TABLE wallet_transfers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	owner_user_id BIGINT NOT NULL,
	transaction_reference VARCHAR(80) NOT NULL,
	idempotency_key VARCHAR(120) NOT NULL,
	sender_account_number VARCHAR(32) NOT NULL,
	receiver_account_number VARCHAR(32) NOT NULL,
	amount NUMERIC(19, 2) NOT NULL,
	currency VARCHAR(3) NOT NULL,
	description VARCHAR(240),
	status VARCHAR(32) NOT NULL,
	failure_reason VARCHAR(500),
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	CONSTRAINT uk_wallet_transfers_reference UNIQUE (transaction_reference),
	CONSTRAINT uk_wallet_transfers_owner_idempotency UNIQUE (owner_user_id, idempotency_key)
);

CREATE INDEX idx_wallet_transfers_owner_created_at
	ON wallet_transfers (owner_user_id, created_at DESC);
