CREATE TABLE wallet_transfer_disputes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	transfer_id BIGINT NOT NULL,
	owner_user_id BIGINT NOT NULL,
	transaction_reference VARCHAR(80) NOT NULL,
	category VARCHAR(80) NOT NULL,
	message VARCHAR(500) NOT NULL,
	status VARCHAR(32) NOT NULL,
	resolution_note VARCHAR(500),
	reviewed_by_user_id BIGINT,
	reviewed_at TIMESTAMP,
	resolved_at TIMESTAMP,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	CONSTRAINT fk_wallet_transfer_disputes_transfer
		FOREIGN KEY (transfer_id) REFERENCES wallet_transfers (id)
);

CREATE INDEX idx_wallet_transfer_disputes_owner_updated_at
	ON wallet_transfer_disputes (owner_user_id, updated_at DESC);

CREATE INDEX idx_wallet_transfer_disputes_status_updated_at
	ON wallet_transfer_disputes (status, updated_at DESC);

CREATE INDEX idx_wallet_transfer_disputes_reference
	ON wallet_transfer_disputes (transaction_reference);
