CREATE TABLE audit_records (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	source_service VARCHAR(80) NOT NULL,
	source_event_id VARCHAR(120) NOT NULL,
	action VARCHAR(80) NOT NULL,
	actor_user_id BIGINT,
	subject_user_id BIGINT,
	aggregate_type VARCHAR(80) NOT NULL,
	aggregate_id VARCHAR(120) NOT NULL,
	summary VARCHAR(500) NOT NULL,
	payload TEXT NOT NULL,
	event_occurred_at TIMESTAMP NOT NULL,
	created_at TIMESTAMP NOT NULL,
	CONSTRAINT uk_audit_records_source_event UNIQUE (source_service, source_event_id)
);

CREATE INDEX idx_audit_records_created_at
	ON audit_records (created_at DESC);

CREATE INDEX idx_audit_records_actor_user_id
	ON audit_records (actor_user_id);

CREATE INDEX idx_audit_records_action
	ON audit_records (action);
